# Generated by Django 4.2 on 2023-04-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('user', '0001_initial'),
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerole',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee'),
        ),
        migrations.AddField(
            model_name='storerole',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='customers',
            field=models.ManyToManyField(related_name='stores', through='store.Balance', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(related_name='stores', through='store.StoreRole', to='user.employee'),
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='stores', through='store.Stock', to='product.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.AddField(
            model_name='balance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='balance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
    ]
