# Generated by Django 4.2 on 2023-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='revenue',
        ),
        migrations.AddField(
            model_name='balance',
            name='sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
