# Generated by Django 4.2 on 2023-05-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_balance_revenue_balance_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='officers', to='store.storerole'),
        ),
    ]
