# Generated by Django 4.2 on 2023-05-10 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('store', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='storerole',
            unique_together={('store', 'user')},
        ),
    ]
