# Generated by Django 4.2 on 2023-05-19 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_balance_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='officer',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('store', models.F('store'))), null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='officers', to='store.storerole'),
        ),
    ]
