# Generated by Django 4.2 on 2023-04-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_order_created_by_alter_restock_created_by_and_more'),
        ('store', '0002_remove_storerole_employee_storerole_user_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
