# Generated by Django 4.2 on 2023-05-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restockitem',
            unique_together={('restock', 'product')},
        ),
    ]
