# Generated by Django 4.2 on 2023-04-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockitem',
            name='restock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.restock'),
        ),
    ]
