# Generated by Django 4.2 on 2023-05-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_comission_alter_order_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comission',
            new_name='commission',
        ),
    ]
