# Generated by Django 4.2 on 2023-04-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_restockitem_restock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='total',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
